# frozen_string_literal: true

# Gem Overview (auto-generated by gem_docs)
#
# * Introduction
# ~fat_date~ collects core extensions for the Date class to make it more useful
# in financial applications, including:
#
# - determining when a =Date= is a federal or NYSE holiday with Presidential
#   decrees included,
# - determining when a =Date= is part of a larger calendar-related "chunk," such
#   as a year, half, quarter, bimonth, month, semimonth, or week,
# - calculating Easter for a =Date's= year, a date on which some "movable
#   feasts" depend, and
# - parsing so-called "specs" that allow the beginning or ending =Date= of a
#   larger period of time to be returned, a facility put to good use in the
#   [[https://github.com/ddoherty03/fat_period][FatPeriod]] gem.

require 'date'
require 'active_support'
require "active_support/isolated_execution_state"
require "active_support/core_ext/date"
require "active_support/core_ext/time"
require "active_support/core_ext/numeric/time"
require "active_support/core_ext/integer/time"

require 'fat_core/string'

require_relative "fat_date/version"
require_relative "fat_date/patches"
require_relative "fat_date/date"
require_relative "fat_date/datetime"

# Gem Overview (extracted from README.org by gem_docs)
#
# * Introduction
# ~fat_date~ collects core extensions for the Date class to make it more useful
# in financial applications, including:
#
# - determining when a =Date= is a federal or NYSE holiday with Presidential
#   decrees included,
# - determining when a =Date= is part of a larger calendar-related "chunk," such
#   as a year, half, quarter, bimonth, month, semimonth, or week,
# - calculating Easter for a =Date's= year, a date on which some "movable
#   feasts" depend, and
# - parsing so-called "specs" that allow the beginning or ending =Date= of a
#   larger period of time to be returned, a facility put to good use in the
#   [[https://github.com/ddoherty03/fat_period][FatPeriod]] gem.
module FatDate
end
